package com.rpll.model;
// Generated Apr 8, 2013 1:49:51 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * AbsencesId generated by hbm2java
 */
public class AbsencesId  implements java.io.Serializable {


     private int periodYear;
     private int studentId;
     private int matkulId;
     private Date absenceDate;

    public AbsencesId() {
    }

    public AbsencesId(int periodYear, int studentId, int matkulId, Date absenceDate) {
       this.periodYear = periodYear;
       this.studentId = studentId;
       this.matkulId = matkulId;
       this.absenceDate = absenceDate;
    }
   
    public int getPeriodYear() {
        return this.periodYear;
    }
    
    public void setPeriodYear(int periodYear) {
        this.periodYear = periodYear;
    }
    public int getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(int studentId) {
        this.studentId = studentId;
    }
    public int getMatkulId() {
        return this.matkulId;
    }
    
    public void setMatkulId(int matkulId) {
        this.matkulId = matkulId;
    }
    public Date getAbsenceDate() {
        return this.absenceDate;
    }
    
    public void setAbsenceDate(Date absenceDate) {
        this.absenceDate = absenceDate;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AbsencesId) ) return false;
		 AbsencesId castOther = ( AbsencesId ) other; 
         
		 return (this.getPeriodYear()==castOther.getPeriodYear())
 && (this.getStudentId()==castOther.getStudentId())
 && (this.getMatkulId()==castOther.getMatkulId())
 && ( (this.getAbsenceDate()==castOther.getAbsenceDate()) || ( this.getAbsenceDate()!=null && castOther.getAbsenceDate()!=null && this.getAbsenceDate().equals(castOther.getAbsenceDate()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPeriodYear();
         result = 37 * result + this.getStudentId();
         result = 37 * result + this.getMatkulId();
         result = 37 * result + ( getAbsenceDate() == null ? 0 : this.getAbsenceDate().hashCode() );
         return result;
   }   


}


