package com.rpll.model;
// Generated Apr 12, 2013 9:26:29 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Angkatan generated by hbm2java
 */
public class Angkatan  implements java.io.Serializable {


     private Integer angkatanId;
     private String angkatanDesc;
     private Set<FeeKuliah> feeKuliahs = new HashSet<FeeKuliah>(0);
     private Set<Faculty> faculties = new HashSet<Faculty>(0);

    public Angkatan() {
    }

	
    public Angkatan(String angkatanDesc) {
        this.angkatanDesc = angkatanDesc;
    }
    public Angkatan(String angkatanDesc, Set<FeeKuliah> feeKuliahs, Set<Faculty> faculties) {
       this.angkatanDesc = angkatanDesc;
       this.feeKuliahs = feeKuliahs;
       this.faculties = faculties;
    }
   
    public Integer getAngkatanId() {
        return this.angkatanId;
    }
    
    public void setAngkatanId(Integer angkatanId) {
        this.angkatanId = angkatanId;
    }
    public String getAngkatanDesc() {
        return this.angkatanDesc;
    }
    
    public void setAngkatanDesc(String angkatanDesc) {
        this.angkatanDesc = angkatanDesc;
    }
    public Set<FeeKuliah> getFeeKuliahs() {
        return this.feeKuliahs;
    }
    
    public void setFeeKuliahs(Set<FeeKuliah> feeKuliahs) {
        this.feeKuliahs = feeKuliahs;
    }
    public Set<Faculty> getFaculties() {
        return this.faculties;
    }
    
    public void setFaculties(Set<Faculty> faculties) {
        this.faculties = faculties;
    }




}


