package com.rpll.model;
// Generated Apr 13, 2013 8:51:10 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Angkatan generated by hbm2java
 */
public class Angkatan  implements java.io.Serializable {


     private Integer angkatanId;
     private String angkatanDesc;
     private Set studentAngkatans = new HashSet(0);
     private Set feeKuliahs = new HashSet(0);
     private Set faculties = new HashSet(0);

    public Angkatan() {
    }

	
    public Angkatan(String angkatanDesc) {
        this.angkatanDesc = angkatanDesc;
    }
    public Angkatan(String angkatanDesc, Set studentAngkatans, Set feeKuliahs, Set faculties) {
       this.angkatanDesc = angkatanDesc;
       this.studentAngkatans = studentAngkatans;
       this.feeKuliahs = feeKuliahs;
       this.faculties = faculties;
    }
   
    public Integer getAngkatanId() {
        return this.angkatanId;
    }
    
    public void setAngkatanId(Integer angkatanId) {
        this.angkatanId = angkatanId;
    }
    public String getAngkatanDesc() {
        return this.angkatanDesc;
    }
    
    public void setAngkatanDesc(String angkatanDesc) {
        this.angkatanDesc = angkatanDesc;
    }
    public Set getStudentAngkatans() {
        return this.studentAngkatans;
    }
    
    public void setStudentAngkatans(Set studentAngkatans) {
        this.studentAngkatans = studentAngkatans;
    }
    public Set getFeeKuliahs() {
        return this.feeKuliahs;
    }
    
    public void setFeeKuliahs(Set feeKuliahs) {
        this.feeKuliahs = feeKuliahs;
    }
    public Set getFaculties() {
        return this.faculties;
    }
    
    public void setFaculties(Set faculties) {
        this.faculties = faculties;
    }




}


