package com.rpll.model;
// Generated Apr 26, 2013 8:19:43 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Announcements generated by hbm2java
 */
public class Announcements  implements java.io.Serializable {


     private Integer annId;
     private Staff staff;
     private Department department;
     private Date datePost;
     private String content;

    public Announcements() {
    }

    public Announcements(Staff staff, Department department, Date datePost, String content) {
       this.staff = staff;
       this.department = department;
       this.datePost = datePost;
       this.content = content;
    }
   
    public Integer getAnnId() {
        return this.annId;
    }
    
    public void setAnnId(Integer annId) {
        this.annId = annId;
    }
    public Staff getStaff() {
        return this.staff;
    }
    
    public void setStaff(Staff staff) {
        this.staff = staff;
    }
    public Department getDepartment() {
        return this.department;
    }
    
    public void setDepartment(Department department) {
        this.department = department;
    }
    public Date getDatePost() {
        return this.datePost;
    }
    
    public void setDatePost(Date datePost) {
        this.datePost = datePost;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }




}


