package com.rpll.model;
// Generated Apr 13, 2013 8:51:10 PM by Hibernate Tools 3.2.1.GA



/**
 * Bobot generated by hbm2java
 */
public class Bobot  implements java.io.Serializable {


     private BobotId id;
     private Matkul matkul;
     private Lectures lectures;
     private Periods periods;
     private double nilai1;
     private double nilai2;
     private double nilai3;
     private double nilai4;
     private double nilai5;
     private double uas;

    public Bobot() {
    }

    public Bobot(BobotId id, Matkul matkul, Lectures lectures, Periods periods, double nilai1, double nilai2, double nilai3, double nilai4, double nilai5, double uas) {
       this.id = id;
       this.matkul = matkul;
       this.lectures = lectures;
       this.periods = periods;
       this.nilai1 = nilai1;
       this.nilai2 = nilai2;
       this.nilai3 = nilai3;
       this.nilai4 = nilai4;
       this.nilai5 = nilai5;
       this.uas = uas;
    }
   
    public BobotId getId() {
        return this.id;
    }
    
    public void setId(BobotId id) {
        this.id = id;
    }
    public Matkul getMatkul() {
        return this.matkul;
    }
    
    public void setMatkul(Matkul matkul) {
        this.matkul = matkul;
    }
    public Lectures getLectures() {
        return this.lectures;
    }
    
    public void setLectures(Lectures lectures) {
        this.lectures = lectures;
    }
    public Periods getPeriods() {
        return this.periods;
    }
    
    public void setPeriods(Periods periods) {
        this.periods = periods;
    }
    public double getNilai1() {
        return this.nilai1;
    }
    
    public void setNilai1(double nilai1) {
        this.nilai1 = nilai1;
    }
    public double getNilai2() {
        return this.nilai2;
    }
    
    public void setNilai2(double nilai2) {
        this.nilai2 = nilai2;
    }
    public double getNilai3() {
        return this.nilai3;
    }
    
    public void setNilai3(double nilai3) {
        this.nilai3 = nilai3;
    }
    public double getNilai4() {
        return this.nilai4;
    }
    
    public void setNilai4(double nilai4) {
        this.nilai4 = nilai4;
    }
    public double getNilai5() {
        return this.nilai5;
    }
    
    public void setNilai5(double nilai5) {
        this.nilai5 = nilai5;
    }
    public double getUas() {
        return this.uas;
    }
    
    public void setUas(double uas) {
        this.uas = uas;
    }




}


