package com.rpll.model;
// Generated Apr 26, 2013 8:19:43 PM by Hibernate Tools 3.2.1.GA



/**
 * ClassSession generated by hbm2java
 */
public class ClassSession  implements java.io.Serializable {


     private ClassSessionId id;
     private Matkul matkul;
     private Lectures lectures;
     private Periods periods;
     private int session;
     private String materiDescription;
     private String assignment;

    public ClassSession() {
    }

    public ClassSession(ClassSessionId id, Matkul matkul, Lectures lectures, Periods periods, int session, String materiDescription, String assignment) {
       this.id = id;
       this.matkul = matkul;
       this.lectures = lectures;
       this.periods = periods;
       this.session = session;
       this.materiDescription = materiDescription;
       this.assignment = assignment;
    }
   
    public ClassSessionId getId() {
        return this.id;
    }
    
    public void setId(ClassSessionId id) {
        this.id = id;
    }
    public Matkul getMatkul() {
        return this.matkul;
    }
    
    public void setMatkul(Matkul matkul) {
        this.matkul = matkul;
    }
    public Lectures getLectures() {
        return this.lectures;
    }
    
    public void setLectures(Lectures lectures) {
        this.lectures = lectures;
    }
    public Periods getPeriods() {
        return this.periods;
    }
    
    public void setPeriods(Periods periods) {
        this.periods = periods;
    }
    public int getSession() {
        return this.session;
    }
    
    public void setSession(int session) {
        this.session = session;
    }
    public String getMateriDescription() {
        return this.materiDescription;
    }
    
    public void setMateriDescription(String materiDescription) {
        this.materiDescription = materiDescription;
    }
    public String getAssignment() {
        return this.assignment;
    }
    
    public void setAssignment(String assignment) {
        this.assignment = assignment;
    }




}


