package com.rpll.model;
// Generated Apr 13, 2013 8:51:10 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Department generated by hbm2java
 */
public class Department  implements java.io.Serializable {


     private Integer departmentId;
     private Lectures lectures;
     private String departmentName;
     private Set lecturesWorks = new HashSet(0);
     private Set announcementses = new HashSet(0);
     private Set matkuls = new HashSet(0);
     private Set studentses = new HashSet(0);
     private Set feeKuliahs = new HashSet(0);
     private Set faculties = new HashSet(0);
     private Set studentAngkatans = new HashSet(0);

    public Department() {
    }

	
    public Department(String departmentName) {
        this.departmentName = departmentName;
    }
    public Department(Lectures lectures, String departmentName, Set lecturesWorks, Set announcementses, Set matkuls, Set studentses, Set feeKuliahs, Set faculties, Set studentAngkatans) {
       this.lectures = lectures;
       this.departmentName = departmentName;
       this.lecturesWorks = lecturesWorks;
       this.announcementses = announcementses;
       this.matkuls = matkuls;
       this.studentses = studentses;
       this.feeKuliahs = feeKuliahs;
       this.faculties = faculties;
       this.studentAngkatans = studentAngkatans;
    }
   
    public Integer getDepartmentId() {
        return this.departmentId;
    }
    
    public void setDepartmentId(Integer departmentId) {
        this.departmentId = departmentId;
    }
    public Lectures getLectures() {
        return this.lectures;
    }
    
    public void setLectures(Lectures lectures) {
        this.lectures = lectures;
    }
    public String getDepartmentName() {
        return this.departmentName;
    }
    
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName;
    }
    public Set getLecturesWorks() {
        return this.lecturesWorks;
    }
    
    public void setLecturesWorks(Set lecturesWorks) {
        this.lecturesWorks = lecturesWorks;
    }
    public Set getAnnouncementses() {
        return this.announcementses;
    }
    
    public void setAnnouncementses(Set announcementses) {
        this.announcementses = announcementses;
    }
    public Set getMatkuls() {
        return this.matkuls;
    }
    
    public void setMatkuls(Set matkuls) {
        this.matkuls = matkuls;
    }
    public Set getStudentses() {
        return this.studentses;
    }
    
    public void setStudentses(Set studentses) {
        this.studentses = studentses;
    }
    public Set getFeeKuliahs() {
        return this.feeKuliahs;
    }
    
    public void setFeeKuliahs(Set feeKuliahs) {
        this.feeKuliahs = feeKuliahs;
    }
    public Set getFaculties() {
        return this.faculties;
    }
    
    public void setFaculties(Set faculties) {
        this.faculties = faculties;
    }
    public Set getStudentAngkatans() {
        return this.studentAngkatans;
    }
    
    public void setStudentAngkatans(Set studentAngkatans) {
        this.studentAngkatans = studentAngkatans;
    }




}


