package com.rpll.model;
// Generated Apr 8, 2013 1:49:51 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Department generated by hbm2java
 */
public class Department  implements java.io.Serializable {


     private Integer departmentId;
     private Lectures lectures;
     private String departmentName;
     private Set<LecturesWork> lecturesWorks = new HashSet<LecturesWork>(0);
     private Set<Announcements> announcementses = new HashSet<Announcements>(0);
     private Set<Matkul> matkuls = new HashSet<Matkul>(0);
     private Set<FeeKuliah> feeKuliahs = new HashSet<FeeKuliah>(0);
     private Set<Faculty> faculties = new HashSet<Faculty>(0);

    public Department() {
    }

	
    public Department(String departmentName) {
        this.departmentName = departmentName;
    }
    public Department(Lectures lectures, String departmentName, Set<LecturesWork> lecturesWorks, Set<Announcements> announcementses, Set<Matkul> matkuls, Set<FeeKuliah> feeKuliahs, Set<Faculty> faculties) {
       this.lectures = lectures;
       this.departmentName = departmentName;
       this.lecturesWorks = lecturesWorks;
       this.announcementses = announcementses;
       this.matkuls = matkuls;
       this.feeKuliahs = feeKuliahs;
       this.faculties = faculties;
    }
   
    public Integer getDepartmentId() {
        return this.departmentId;
    }
    
    public void setDepartmentId(Integer departmentId) {
        this.departmentId = departmentId;
    }
    public Lectures getLectures() {
        return this.lectures;
    }
    
    public void setLectures(Lectures lectures) {
        this.lectures = lectures;
    }
    public String getDepartmentName() {
        return this.departmentName;
    }
    
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName;
    }
    public Set<LecturesWork> getLecturesWorks() {
        return this.lecturesWorks;
    }
    
    public void setLecturesWorks(Set<LecturesWork> lecturesWorks) {
        this.lecturesWorks = lecturesWorks;
    }
    public Set<Announcements> getAnnouncementses() {
        return this.announcementses;
    }
    
    public void setAnnouncementses(Set<Announcements> announcementses) {
        this.announcementses = announcementses;
    }
    public Set<Matkul> getMatkuls() {
        return this.matkuls;
    }
    
    public void setMatkuls(Set<Matkul> matkuls) {
        this.matkuls = matkuls;
    }
    public Set<FeeKuliah> getFeeKuliahs() {
        return this.feeKuliahs;
    }
    
    public void setFeeKuliahs(Set<FeeKuliah> feeKuliahs) {
        this.feeKuliahs = feeKuliahs;
    }
    public Set<Faculty> getFaculties() {
        return this.faculties;
    }
    
    public void setFaculties(Set<Faculty> faculties) {
        this.faculties = faculties;
    }




}


