package com.rpll.model;
// Generated Apr 15, 2013 2:00:19 PM by Hibernate Tools 3.2.1.GA



/**
 * Faculty generated by hbm2java
 */
public class Faculty  implements java.io.Serializable {


     private FacultyId id;
     private University university;
     private Angkatan angkatan;
     private Department department;

    public Faculty() {
    }

    public Faculty(FacultyId id, University university, Angkatan angkatan, Department department) {
       this.id = id;
       this.university = university;
       this.angkatan = angkatan;
       this.department = department;
    }
   
    public FacultyId getId() {
        return this.id;
    }
    
    public void setId(FacultyId id) {
        this.id = id;
    }
    public University getUniversity() {
        return this.university;
    }
    
    public void setUniversity(University university) {
        this.university = university;
    }
    public Angkatan getAngkatan() {
        return this.angkatan;
    }
    
    public void setAngkatan(Angkatan angkatan) {
        this.angkatan = angkatan;
    }
    public Department getDepartment() {
        return this.department;
    }
    
    public void setDepartment(Department department) {
        this.department = department;
    }




}


