package com.rpll.model;
// Generated Apr 13, 2013 8:51:10 PM by Hibernate Tools 3.2.1.GA



/**
 * FeeKuliah generated by hbm2java
 */
public class FeeKuliah  implements java.io.Serializable {


     private FeeKuliahId id;
     private Angkatan angkatan;
     private Department department;
     private double feeSks;
     private double feeLab;
     private double feeKemahasiswaan;
     private double feeTetap;

    public FeeKuliah() {
    }

    public FeeKuliah(FeeKuliahId id, Angkatan angkatan, Department department, double feeSks, double feeLab, double feeKemahasiswaan, double feeTetap) {
       this.id = id;
       this.angkatan = angkatan;
       this.department = department;
       this.feeSks = feeSks;
       this.feeLab = feeLab;
       this.feeKemahasiswaan = feeKemahasiswaan;
       this.feeTetap = feeTetap;
    }
   
    public FeeKuliahId getId() {
        return this.id;
    }
    
    public void setId(FeeKuliahId id) {
        this.id = id;
    }
    public Angkatan getAngkatan() {
        return this.angkatan;
    }
    
    public void setAngkatan(Angkatan angkatan) {
        this.angkatan = angkatan;
    }
    public Department getDepartment() {
        return this.department;
    }
    
    public void setDepartment(Department department) {
        this.department = department;
    }
    public double getFeeSks() {
        return this.feeSks;
    }
    
    public void setFeeSks(double feeSks) {
        this.feeSks = feeSks;
    }
    public double getFeeLab() {
        return this.feeLab;
    }
    
    public void setFeeLab(double feeLab) {
        this.feeLab = feeLab;
    }
    public double getFeeKemahasiswaan() {
        return this.feeKemahasiswaan;
    }
    
    public void setFeeKemahasiswaan(double feeKemahasiswaan) {
        this.feeKemahasiswaan = feeKemahasiswaan;
    }
    public double getFeeTetap() {
        return this.feeTetap;
    }
    
    public void setFeeTetap(double feeTetap) {
        this.feeTetap = feeTetap;
    }




}


