package com.rpll.model;
// Generated Apr 13, 2013 8:51:10 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Jobs generated by hbm2java
 */
public class Jobs  implements java.io.Serializable {


     private Integer jobId;
     private String jobName;
     private Set staffs = new HashSet(0);

    public Jobs() {
    }

	
    public Jobs(String jobName) {
        this.jobName = jobName;
    }
    public Jobs(String jobName, Set staffs) {
       this.jobName = jobName;
       this.staffs = staffs;
    }
   
    public Integer getJobId() {
        return this.jobId;
    }
    
    public void setJobId(Integer jobId) {
        this.jobId = jobId;
    }
    public String getJobName() {
        return this.jobName;
    }
    
    public void setJobName(String jobName) {
        this.jobName = jobName;
    }
    public Set getStaffs() {
        return this.staffs;
    }
    
    public void setStaffs(Set staffs) {
        this.staffs = staffs;
    }




}


