package com.rpll.model;
// Generated Apr 26, 2013 8:19:43 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Keuangan generated by hbm2java
 */
public class Keuangan  implements java.io.Serializable {


     private Integer keuanganId;
     private Students students;
     private Date keuanganDate;
     private String laporan;
     private int stat;

    public Keuangan() {
    }

    public Keuangan(Students students, Date keuanganDate, String laporan, int stat) {
       this.students = students;
       this.keuanganDate = keuanganDate;
       this.laporan = laporan;
       this.stat = stat;
    }
   
    public Integer getKeuanganId() {
        return this.keuanganId;
    }
    
    public void setKeuanganId(Integer keuanganId) {
        this.keuanganId = keuanganId;
    }
    public Students getStudents() {
        return this.students;
    }
    
    public void setStudents(Students students) {
        this.students = students;
    }
    public Date getKeuanganDate() {
        return this.keuanganDate;
    }
    
    public void setKeuanganDate(Date keuanganDate) {
        this.keuanganDate = keuanganDate;
    }
    public String getLaporan() {
        return this.laporan;
    }
    
    public void setLaporan(String laporan) {
        this.laporan = laporan;
    }
    public int getStat() {
        return this.stat;
    }
    
    public void setStat(int stat) {
        this.stat = stat;
    }




}


