package com.rpll.model;
// Generated Apr 13, 2013 8:51:10 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Lectures generated by hbm2java
 */
public class Lectures  implements java.io.Serializable {


     private Integer lectureId;
     private String lectureName;
     private String lectureAddress;
     private String lectureTelp;
     private String lectureEmail;
     private Set lecturesWorks = new HashSet(0);
     private Set lecturesEdus = new HashSet(0);
     private Set studentses = new HashSet(0);
     private Set teachPeriods = new HashSet(0);
     private Set takeRoomses = new HashSet(0);
     private Set classSessions = new HashSet(0);
     private Set bobots = new HashSet(0);
     private Set departments = new HashSet(0);

    public Lectures() {
    }

	
    public Lectures(String lectureName, String lectureAddress, String lectureTelp, String lectureEmail) {
        this.lectureName = lectureName;
        this.lectureAddress = lectureAddress;
        this.lectureTelp = lectureTelp;
        this.lectureEmail = lectureEmail;
    }
    public Lectures(String lectureName, String lectureAddress, String lectureTelp, String lectureEmail, Set lecturesWorks, Set lecturesEdus, Set studentses, Set teachPeriods, Set takeRoomses, Set classSessions, Set bobots, Set departments) {
       this.lectureName = lectureName;
       this.lectureAddress = lectureAddress;
       this.lectureTelp = lectureTelp;
       this.lectureEmail = lectureEmail;
       this.lecturesWorks = lecturesWorks;
       this.lecturesEdus = lecturesEdus;
       this.studentses = studentses;
       this.teachPeriods = teachPeriods;
       this.takeRoomses = takeRoomses;
       this.classSessions = classSessions;
       this.bobots = bobots;
       this.departments = departments;
    }
   
    public Integer getLectureId() {
        return this.lectureId;
    }
    
    public void setLectureId(Integer lectureId) {
        this.lectureId = lectureId;
    }
    public String getLectureName() {
        return this.lectureName;
    }
    
    public void setLectureName(String lectureName) {
        this.lectureName = lectureName;
    }
    public String getLectureAddress() {
        return this.lectureAddress;
    }
    
    public void setLectureAddress(String lectureAddress) {
        this.lectureAddress = lectureAddress;
    }
    public String getLectureTelp() {
        return this.lectureTelp;
    }
    
    public void setLectureTelp(String lectureTelp) {
        this.lectureTelp = lectureTelp;
    }
    public String getLectureEmail() {
        return this.lectureEmail;
    }
    
    public void setLectureEmail(String lectureEmail) {
        this.lectureEmail = lectureEmail;
    }
    public Set getLecturesWorks() {
        return this.lecturesWorks;
    }
    
    public void setLecturesWorks(Set lecturesWorks) {
        this.lecturesWorks = lecturesWorks;
    }
    public Set getLecturesEdus() {
        return this.lecturesEdus;
    }
    
    public void setLecturesEdus(Set lecturesEdus) {
        this.lecturesEdus = lecturesEdus;
    }
    public Set getStudentses() {
        return this.studentses;
    }
    
    public void setStudentses(Set studentses) {
        this.studentses = studentses;
    }
    public Set getTeachPeriods() {
        return this.teachPeriods;
    }
    
    public void setTeachPeriods(Set teachPeriods) {
        this.teachPeriods = teachPeriods;
    }
    public Set getTakeRoomses() {
        return this.takeRoomses;
    }
    
    public void setTakeRoomses(Set takeRoomses) {
        this.takeRoomses = takeRoomses;
    }
    public Set getClassSessions() {
        return this.classSessions;
    }
    
    public void setClassSessions(Set classSessions) {
        this.classSessions = classSessions;
    }
    public Set getBobots() {
        return this.bobots;
    }
    
    public void setBobots(Set bobots) {
        this.bobots = bobots;
    }
    public Set getDepartments() {
        return this.departments;
    }
    
    public void setDepartments(Set departments) {
        this.departments = departments;
    }




}


