package com.rpll.model;
// Generated Apr 8, 2013 1:49:51 PM by Hibernate Tools 3.2.1.GA



/**
 * LecturesWorkId generated by hbm2java
 */
public class LecturesWorkId  implements java.io.Serializable {


     private int lectureId;
     private int departmentId;

    public LecturesWorkId() {
    }

    public LecturesWorkId(int lectureId, int departmentId) {
       this.lectureId = lectureId;
       this.departmentId = departmentId;
    }
   
    public int getLectureId() {
        return this.lectureId;
    }
    
    public void setLectureId(int lectureId) {
        this.lectureId = lectureId;
    }
    public int getDepartmentId() {
        return this.departmentId;
    }
    
    public void setDepartmentId(int departmentId) {
        this.departmentId = departmentId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LecturesWorkId) ) return false;
		 LecturesWorkId castOther = ( LecturesWorkId ) other; 
         
		 return (this.getLectureId()==castOther.getLectureId())
 && (this.getDepartmentId()==castOther.getDepartmentId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getLectureId();
         result = 37 * result + this.getDepartmentId();
         return result;
   }   


}


