package com.rpll.model;
// Generated Apr 12, 2013 9:26:29 PM by Hibernate Tools 3.2.1.GA



/**
 * LecturesEdu generated by hbm2java
 */
public class LecturesEdu  implements java.io.Serializable {


     private LecturesEduId id;
     private Lectures lectures;

    public LecturesEdu() {
    }

    public LecturesEdu(LecturesEduId id, Lectures lectures) {
       this.id = id;
       this.lectures = lectures;
    }
   
    public LecturesEduId getId() {
        return this.id;
    }
    
    public void setId(LecturesEduId id) {
        this.id = id;
    }
    public Lectures getLectures() {
        return this.lectures;
    }
    
    public void setLectures(Lectures lectures) {
        this.lectures = lectures;
    }




}


