package com.rpll.model;
// Generated Apr 15, 2013 2:00:19 PM by Hibernate Tools 3.2.1.GA



/**
 * LecturesWork generated by hbm2java
 */
public class LecturesWork  implements java.io.Serializable {


     private LecturesWorkId id;
     private Lectures lectures;
     private Department department;
     private String lectureType;
     private double lectureSalary;

    public LecturesWork() {
    }

    public LecturesWork(LecturesWorkId id, Lectures lectures, Department department, String lectureType, double lectureSalary) {
       this.id = id;
       this.lectures = lectures;
       this.department = department;
       this.lectureType = lectureType;
       this.lectureSalary = lectureSalary;
    }
   
    public LecturesWorkId getId() {
        return this.id;
    }
    
    public void setId(LecturesWorkId id) {
        this.id = id;
    }
    public Lectures getLectures() {
        return this.lectures;
    }
    
    public void setLectures(Lectures lectures) {
        this.lectures = lectures;
    }
    public Department getDepartment() {
        return this.department;
    }
    
    public void setDepartment(Department department) {
        this.department = department;
    }
    public String getLectureType() {
        return this.lectureType;
    }
    
    public void setLectureType(String lectureType) {
        this.lectureType = lectureType;
    }
    public double getLectureSalary() {
        return this.lectureSalary;
    }
    
    public void setLectureSalary(double lectureSalary) {
        this.lectureSalary = lectureSalary;
    }




}


