package com.rpll.model;
// Generated Apr 26, 2013 8:19:43 PM by Hibernate Tools 3.2.1.GA



/**
 * MatkulDeptId generated by hbm2java
 */
public class MatkulDeptId  implements java.io.Serializable {


     private int matkulId;
     private int departmentId;

    public MatkulDeptId() {
    }

    public MatkulDeptId(int matkulId, int departmentId) {
       this.matkulId = matkulId;
       this.departmentId = departmentId;
    }
   
    public int getMatkulId() {
        return this.matkulId;
    }
    
    public void setMatkulId(int matkulId) {
        this.matkulId = matkulId;
    }
    public int getDepartmentId() {
        return this.departmentId;
    }
    
    public void setDepartmentId(int departmentId) {
        this.departmentId = departmentId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MatkulDeptId) ) return false;
		 MatkulDeptId castOther = ( MatkulDeptId ) other; 
         
		 return (this.getMatkulId()==castOther.getMatkulId())
 && (this.getDepartmentId()==castOther.getDepartmentId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getMatkulId();
         result = 37 * result + this.getDepartmentId();
         return result;
   }   


}


