package com.rpll.model;
// Generated Apr 15, 2013 2:00:19 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * MatkulMandatory generated by hbm2java
 */
public class MatkulMandatory  implements java.io.Serializable {


     private Integer mandatoryId;
     private String mandatoryCode;
     private String mandatoryName;
     private Set<MatkulDept> matkulDepts = new HashSet<MatkulDept>(0);

    public MatkulMandatory() {
    }

	
    public MatkulMandatory(String mandatoryCode, String mandatoryName) {
        this.mandatoryCode = mandatoryCode;
        this.mandatoryName = mandatoryName;
    }
    public MatkulMandatory(String mandatoryCode, String mandatoryName, Set<MatkulDept> matkulDepts) {
       this.mandatoryCode = mandatoryCode;
       this.mandatoryName = mandatoryName;
       this.matkulDepts = matkulDepts;
    }
   
    public Integer getMandatoryId() {
        return this.mandatoryId;
    }
    
    public void setMandatoryId(Integer mandatoryId) {
        this.mandatoryId = mandatoryId;
    }
    public String getMandatoryCode() {
        return this.mandatoryCode;
    }
    
    public void setMandatoryCode(String mandatoryCode) {
        this.mandatoryCode = mandatoryCode;
    }
    public String getMandatoryName() {
        return this.mandatoryName;
    }
    
    public void setMandatoryName(String mandatoryName) {
        this.mandatoryName = mandatoryName;
    }
    public Set<MatkulDept> getMatkulDepts() {
        return this.matkulDepts;
    }
    
    public void setMatkulDepts(Set<MatkulDept> matkulDepts) {
        this.matkulDepts = matkulDepts;
    }




}


