package com.rpll.model;
// Generated Apr 26, 2013 8:19:43 PM by Hibernate Tools 3.2.1.GA



/**
 * MatkulDept generated by hbm2java
 */
public class MatkulDept  implements java.io.Serializable {


     private MatkulDeptId id;
     private Matkul matkul;
     private MatkulMandatory matkulMandatory;
     private Department department;
     private int bobotSks;
     private int matkulSem;

    public MatkulDept() {
    }

    public MatkulDept(MatkulDeptId id, Matkul matkul, MatkulMandatory matkulMandatory, Department department, int bobotSks, int matkulSem) {
       this.id = id;
       this.matkul = matkul;
       this.matkulMandatory = matkulMandatory;
       this.department = department;
       this.bobotSks = bobotSks;
       this.matkulSem = matkulSem;
    }
   
    public MatkulDeptId getId() {
        return this.id;
    }
    
    public void setId(MatkulDeptId id) {
        this.id = id;
    }
    public Matkul getMatkul() {
        return this.matkul;
    }
    
    public void setMatkul(Matkul matkul) {
        this.matkul = matkul;
    }
    public MatkulMandatory getMatkulMandatory() {
        return this.matkulMandatory;
    }
    
    public void setMatkulMandatory(MatkulMandatory matkulMandatory) {
        this.matkulMandatory = matkulMandatory;
    }
    public Department getDepartment() {
        return this.department;
    }
    
    public void setDepartment(Department department) {
        this.department = department;
    }
    public int getBobotSks() {
        return this.bobotSks;
    }
    
    public void setBobotSks(int bobotSks) {
        this.bobotSks = bobotSks;
    }
    public int getMatkulSem() {
        return this.matkulSem;
    }
    
    public void setMatkulSem(int matkulSem) {
        this.matkulSem = matkulSem;
    }




}


