package com.rpll.model;
// Generated Apr 13, 2013 8:51:10 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Matkul generated by hbm2java
 */
public class Matkul  implements java.io.Serializable {


     private Integer matkulId;
     private MatkulType matkulType;
     private String matkulName;
     private int bobotSks;
     private Set markses = new HashSet(0);
     private Set teachPeriods = new HashSet(0);
     private Set takeRoomses = new HashSet(0);
     private Set departments = new HashSet(0);
     private Set takeMatkulPeriods = new HashSet(0);
     private Set classSessions = new HashSet(0);
     private Set bobots = new HashSet(0);
     private Set moduls = new HashSet(0);
     private Set absenceses = new HashSet(0);

    public Matkul() {
    }

	
    public Matkul(MatkulType matkulType, String matkulName, int bobotSks) {
        this.matkulType = matkulType;
        this.matkulName = matkulName;
        this.bobotSks = bobotSks;
    }
    public Matkul(MatkulType matkulType, String matkulName, int bobotSks, Set markses, Set teachPeriods, Set takeRoomses, Set departments, Set takeMatkulPeriods, Set classSessions, Set bobots, Set moduls, Set absenceses) {
       this.matkulType = matkulType;
       this.matkulName = matkulName;
       this.bobotSks = bobotSks;
       this.markses = markses;
       this.teachPeriods = teachPeriods;
       this.takeRoomses = takeRoomses;
       this.departments = departments;
       this.takeMatkulPeriods = takeMatkulPeriods;
       this.classSessions = classSessions;
       this.bobots = bobots;
       this.moduls = moduls;
       this.absenceses = absenceses;
    }
   
    public Integer getMatkulId() {
        return this.matkulId;
    }
    
    public void setMatkulId(Integer matkulId) {
        this.matkulId = matkulId;
    }
    public MatkulType getMatkulType() {
        return this.matkulType;
    }
    
    public void setMatkulType(MatkulType matkulType) {
        this.matkulType = matkulType;
    }
    public String getMatkulName() {
        return this.matkulName;
    }
    
    public void setMatkulName(String matkulName) {
        this.matkulName = matkulName;
    }
    public int getBobotSks() {
        return this.bobotSks;
    }
    
    public void setBobotSks(int bobotSks) {
        this.bobotSks = bobotSks;
    }
    public Set getMarkses() {
        return this.markses;
    }
    
    public void setMarkses(Set markses) {
        this.markses = markses;
    }
    public Set getTeachPeriods() {
        return this.teachPeriods;
    }
    
    public void setTeachPeriods(Set teachPeriods) {
        this.teachPeriods = teachPeriods;
    }
    public Set getTakeRoomses() {
        return this.takeRoomses;
    }
    
    public void setTakeRoomses(Set takeRoomses) {
        this.takeRoomses = takeRoomses;
    }
    public Set getDepartments() {
        return this.departments;
    }
    
    public void setDepartments(Set departments) {
        this.departments = departments;
    }
    public Set getTakeMatkulPeriods() {
        return this.takeMatkulPeriods;
    }
    
    public void setTakeMatkulPeriods(Set takeMatkulPeriods) {
        this.takeMatkulPeriods = takeMatkulPeriods;
    }
    public Set getClassSessions() {
        return this.classSessions;
    }
    
    public void setClassSessions(Set classSessions) {
        this.classSessions = classSessions;
    }
    public Set getBobots() {
        return this.bobots;
    }
    
    public void setBobots(Set bobots) {
        this.bobots = bobots;
    }
    public Set getModuls() {
        return this.moduls;
    }
    
    public void setModuls(Set moduls) {
        this.moduls = moduls;
    }
    public Set getAbsenceses() {
        return this.absenceses;
    }
    
    public void setAbsenceses(Set absenceses) {
        this.absenceses = absenceses;
    }




}


