package com.rpll.model;
// Generated Apr 13, 2013 8:51:10 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Students generated by hbm2java
 */
public class Students  implements java.io.Serializable {


     private int studentId;
     private Lectures lectures;
     private Department department;
     private String studentName;
     private String studentAddress;
     private int studentTelp;
     private String studentEmail;
     private int studentStatus;
     private String studentPass;
     private Set markses = new HashSet(0);
     private Set studentAngkatans = new HashSet(0);
     private Set keuangans = new HashSet(0);
     private Set absenceses = new HashSet(0);
     private Set takeMatkulPeriods = new HashSet(0);

    public Students() {
    }

	
    public Students(int studentId, Lectures lectures, Department department, String studentName, String studentAddress, int studentTelp, String studentEmail, int studentStatus, String studentPass) {
        this.studentId = studentId;
        this.lectures = lectures;
        this.department = department;
        this.studentName = studentName;
        this.studentAddress = studentAddress;
        this.studentTelp = studentTelp;
        this.studentEmail = studentEmail;
        this.studentStatus = studentStatus;
        this.studentPass = studentPass;
    }
    public Students(int studentId, Lectures lectures, Department department, String studentName, String studentAddress, int studentTelp, String studentEmail, int studentStatus, String studentPass, Set markses, Set studentAngkatans, Set keuangans, Set absenceses, Set takeMatkulPeriods) {
       this.studentId = studentId;
       this.lectures = lectures;
       this.department = department;
       this.studentName = studentName;
       this.studentAddress = studentAddress;
       this.studentTelp = studentTelp;
       this.studentEmail = studentEmail;
       this.studentStatus = studentStatus;
       this.studentPass = studentPass;
       this.markses = markses;
       this.studentAngkatans = studentAngkatans;
       this.keuangans = keuangans;
       this.absenceses = absenceses;
       this.takeMatkulPeriods = takeMatkulPeriods;
    }
   
    public int getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(int studentId) {
        this.studentId = studentId;
    }
    public Lectures getLectures() {
        return this.lectures;
    }
    
    public void setLectures(Lectures lectures) {
        this.lectures = lectures;
    }
    public Department getDepartment() {
        return this.department;
    }
    
    public void setDepartment(Department department) {
        this.department = department;
    }
    public String getStudentName() {
        return this.studentName;
    }
    
    public void setStudentName(String studentName) {
        this.studentName = studentName;
    }
    public String getStudentAddress() {
        return this.studentAddress;
    }
    
    public void setStudentAddress(String studentAddress) {
        this.studentAddress = studentAddress;
    }
    public int getStudentTelp() {
        return this.studentTelp;
    }
    
    public void setStudentTelp(int studentTelp) {
        this.studentTelp = studentTelp;
    }
    public String getStudentEmail() {
        return this.studentEmail;
    }
    
    public void setStudentEmail(String studentEmail) {
        this.studentEmail = studentEmail;
    }
    public int getStudentStatus() {
        return this.studentStatus;
    }
    
    public void setStudentStatus(int studentStatus) {
        this.studentStatus = studentStatus;
    }
    public String getStudentPass() {
        return this.studentPass;
    }
    
    public void setStudentPass(String studentPass) {
        this.studentPass = studentPass;
    }
    public Set getMarkses() {
        return this.markses;
    }
    
    public void setMarkses(Set markses) {
        this.markses = markses;
    }
    public Set getStudentAngkatans() {
        return this.studentAngkatans;
    }
    
    public void setStudentAngkatans(Set studentAngkatans) {
        this.studentAngkatans = studentAngkatans;
    }
    public Set getKeuangans() {
        return this.keuangans;
    }
    
    public void setKeuangans(Set keuangans) {
        this.keuangans = keuangans;
    }
    public Set getAbsenceses() {
        return this.absenceses;
    }
    
    public void setAbsenceses(Set absenceses) {
        this.absenceses = absenceses;
    }
    public Set getTakeMatkulPeriods() {
        return this.takeMatkulPeriods;
    }
    
    public void setTakeMatkulPeriods(Set takeMatkulPeriods) {
        this.takeMatkulPeriods = takeMatkulPeriods;
    }




}


