package com.rpll.model;
// Generated Apr 12, 2013 9:26:29 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Students generated by hbm2java
 */
public class Students  implements java.io.Serializable {


     private int studentId;
     private Lectures lectures;
     private Department department;
     private String studentName;
     private String studentAddress;
     private int studentTelp;
     private String studentEmail;
     private int studentStatus;
     private Set<Marks> markses = new HashSet<Marks>(0);
     private Set<Keuangan> keuangans = new HashSet<Keuangan>(0);
     private Set<Absences> absenceses = new HashSet<Absences>(0);
     private Set<TakeMatkulPeriod> takeMatkulPeriods = new HashSet<TakeMatkulPeriod>(0);

    public Students() {
    }

	
    public Students(int studentId, Lectures lectures, Department department, String studentName, String studentAddress, int studentTelp, String studentEmail, int studentStatus) {
        this.studentId = studentId;
        this.lectures = lectures;
        this.department = department;
        this.studentName = studentName;
        this.studentAddress = studentAddress;
        this.studentTelp = studentTelp;
        this.studentEmail = studentEmail;
        this.studentStatus = studentStatus;
    }
    public Students(int studentId, Lectures lectures, Department department, String studentName, String studentAddress, int studentTelp, String studentEmail, int studentStatus, Set<Marks> markses, Set<Keuangan> keuangans, Set<Absences> absenceses, Set<TakeMatkulPeriod> takeMatkulPeriods) {
       this.studentId = studentId;
       this.lectures = lectures;
       this.department = department;
       this.studentName = studentName;
       this.studentAddress = studentAddress;
       this.studentTelp = studentTelp;
       this.studentEmail = studentEmail;
       this.studentStatus = studentStatus;
       this.markses = markses;
       this.keuangans = keuangans;
       this.absenceses = absenceses;
       this.takeMatkulPeriods = takeMatkulPeriods;
    }
   
    public int getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(int studentId) {
        this.studentId = studentId;
    }
    public Lectures getLectures() {
        return this.lectures;
    }
    
    public void setLectures(Lectures lectures) {
        this.lectures = lectures;
    }
    public Department getDepartment() {
        return this.department;
    }
    
    public void setDepartment(Department department) {
        this.department = department;
    }
    public String getStudentName() {
        return this.studentName;
    }
    
    public void setStudentName(String studentName) {
        this.studentName = studentName;
    }
    public String getStudentAddress() {
        return this.studentAddress;
    }
    
    public void setStudentAddress(String studentAddress) {
        this.studentAddress = studentAddress;
    }
    public int getStudentTelp() {
        return this.studentTelp;
    }
    
    public void setStudentTelp(int studentTelp) {
        this.studentTelp = studentTelp;
    }
    public String getStudentEmail() {
        return this.studentEmail;
    }
    
    public void setStudentEmail(String studentEmail) {
        this.studentEmail = studentEmail;
    }
    public int getStudentStatus() {
        return this.studentStatus;
    }
    
    public void setStudentStatus(int studentStatus) {
        this.studentStatus = studentStatus;
    }
    public Set<Marks> getMarkses() {
        return this.markses;
    }
    
    public void setMarkses(Set<Marks> markses) {
        this.markses = markses;
    }
    public Set<Keuangan> getKeuangans() {
        return this.keuangans;
    }
    
    public void setKeuangans(Set<Keuangan> keuangans) {
        this.keuangans = keuangans;
    }
    public Set<Absences> getAbsenceses() {
        return this.absenceses;
    }
    
    public void setAbsenceses(Set<Absences> absenceses) {
        this.absenceses = absenceses;
    }
    public Set<TakeMatkulPeriod> getTakeMatkulPeriods() {
        return this.takeMatkulPeriods;
    }
    
    public void setTakeMatkulPeriods(Set<TakeMatkulPeriod> takeMatkulPeriods) {
        this.takeMatkulPeriods = takeMatkulPeriods;
    }




}


