package com.rpll.model;
// Generated Apr 26, 2013 8:19:43 PM by Hibernate Tools 3.2.1.GA



/**
 * StudentAngkatan generated by hbm2java
 */
public class StudentAngkatan  implements java.io.Serializable {


     private StudentAngkatanId id;
     private Students students;
     private Angkatan angkatan;
     private Department department;

    public StudentAngkatan() {
    }

    public StudentAngkatan(StudentAngkatanId id, Students students, Angkatan angkatan, Department department) {
       this.id = id;
       this.students = students;
       this.angkatan = angkatan;
       this.department = department;
    }
   
    public StudentAngkatanId getId() {
        return this.id;
    }
    
    public void setId(StudentAngkatanId id) {
        this.id = id;
    }
    public Students getStudents() {
        return this.students;
    }
    
    public void setStudents(Students students) {
        this.students = students;
    }
    public Angkatan getAngkatan() {
        return this.angkatan;
    }
    
    public void setAngkatan(Angkatan angkatan) {
        this.angkatan = angkatan;
    }
    public Department getDepartment() {
        return this.department;
    }
    
    public void setDepartment(Department department) {
        this.department = department;
    }




}


