package com.rpll.model;
// Generated Apr 13, 2013 8:51:10 PM by Hibernate Tools 3.2.1.GA



/**
 * TeachPeriodId generated by hbm2java
 */
public class TeachPeriodId  implements java.io.Serializable {


     private int lectureId;
     private int matkulId;
     private int periodId;

    public TeachPeriodId() {
    }

    public TeachPeriodId(int lectureId, int matkulId, int periodId) {
       this.lectureId = lectureId;
       this.matkulId = matkulId;
       this.periodId = periodId;
    }
   
    public int getLectureId() {
        return this.lectureId;
    }
    
    public void setLectureId(int lectureId) {
        this.lectureId = lectureId;
    }
    public int getMatkulId() {
        return this.matkulId;
    }
    
    public void setMatkulId(int matkulId) {
        this.matkulId = matkulId;
    }
    public int getPeriodId() {
        return this.periodId;
    }
    
    public void setPeriodId(int periodId) {
        this.periodId = periodId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TeachPeriodId) ) return false;
		 TeachPeriodId castOther = ( TeachPeriodId ) other; 
         
		 return (this.getLectureId()==castOther.getLectureId())
 && (this.getMatkulId()==castOther.getMatkulId())
 && (this.getPeriodId()==castOther.getPeriodId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getLectureId();
         result = 37 * result + this.getMatkulId();
         result = 37 * result + this.getPeriodId();
         return result;
   }   


}


