package com.rpll.model;
// Generated Apr 8, 2013 1:49:51 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * University generated by hbm2java
 */
public class University  implements java.io.Serializable {


     private Integer univId;
     private String univName;
     private String univAddress;
     private int univTelp;
     private String univEmail;
     private String univHomepage;
     private Set<Staff> staffs = new HashSet<Staff>(0);
     private Set<Faculty> faculties = new HashSet<Faculty>(0);

    public University() {
    }

	
    public University(String univName, String univAddress, int univTelp, String univEmail, String univHomepage) {
        this.univName = univName;
        this.univAddress = univAddress;
        this.univTelp = univTelp;
        this.univEmail = univEmail;
        this.univHomepage = univHomepage;
    }
    public University(String univName, String univAddress, int univTelp, String univEmail, String univHomepage, Set<Staff> staffs, Set<Faculty> faculties) {
       this.univName = univName;
       this.univAddress = univAddress;
       this.univTelp = univTelp;
       this.univEmail = univEmail;
       this.univHomepage = univHomepage;
       this.staffs = staffs;
       this.faculties = faculties;
    }
   
    public Integer getUnivId() {
        return this.univId;
    }
    
    public void setUnivId(Integer univId) {
        this.univId = univId;
    }
    public String getUnivName() {
        return this.univName;
    }
    
    public void setUnivName(String univName) {
        this.univName = univName;
    }
    public String getUnivAddress() {
        return this.univAddress;
    }
    
    public void setUnivAddress(String univAddress) {
        this.univAddress = univAddress;
    }
    public int getUnivTelp() {
        return this.univTelp;
    }
    
    public void setUnivTelp(int univTelp) {
        this.univTelp = univTelp;
    }
    public String getUnivEmail() {
        return this.univEmail;
    }
    
    public void setUnivEmail(String univEmail) {
        this.univEmail = univEmail;
    }
    public String getUnivHomepage() {
        return this.univHomepage;
    }
    
    public void setUnivHomepage(String univHomepage) {
        this.univHomepage = univHomepage;
    }
    public Set<Staff> getStaffs() {
        return this.staffs;
    }
    
    public void setStaffs(Set<Staff> staffs) {
        this.staffs = staffs;
    }
    public Set<Faculty> getFaculties() {
        return this.faculties;
    }
    
    public void setFaculties(Set<Faculty> faculties) {
        this.faculties = faculties;
    }




}


