package com.rpll.model;
// Generated Apr 12, 2013 9:26:29 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * University generated by hbm2java
 */
public class University  implements java.io.Serializable {


     private Integer univId;
     private String univName;
     private String univAddress;
     private String univTelp;
     private String univEmail;
     private String univHomepage;
     private int noAkreditasi;
     private String akreditasi;
     private Date foundDate;
     private String rector;
     private Set<Staff> staffs = new HashSet<Staff>(0);
     private Set<Faculty> faculties = new HashSet<Faculty>(0);

    public University() {
    }

	
    public University(String univName, String univAddress, String univTelp, String univEmail, String univHomepage, int noAkreditasi, String akreditasi, Date foundDate, String rector) {
        this.univName = univName;
        this.univAddress = univAddress;
        this.univTelp = univTelp;
        this.univEmail = univEmail;
        this.univHomepage = univHomepage;
        this.noAkreditasi = noAkreditasi;
        this.akreditasi = akreditasi;
        this.foundDate = foundDate;
        this.rector = rector;
    }
    public University(String univName, String univAddress, String univTelp, String univEmail, String univHomepage, int noAkreditasi, String akreditasi, Date foundDate, String rector, Set<Staff> staffs, Set<Faculty> faculties) {
       this.univName = univName;
       this.univAddress = univAddress;
       this.univTelp = univTelp;
       this.univEmail = univEmail;
       this.univHomepage = univHomepage;
       this.noAkreditasi = noAkreditasi;
       this.akreditasi = akreditasi;
       this.foundDate = foundDate;
       this.rector = rector;
       this.staffs = staffs;
       this.faculties = faculties;
    }
   
    public Integer getUnivId() {
        return this.univId;
    }
    
    public void setUnivId(Integer univId) {
        this.univId = univId;
    }
    public String getUnivName() {
        return this.univName;
    }
    
    public void setUnivName(String univName) {
        this.univName = univName;
    }
    public String getUnivAddress() {
        return this.univAddress;
    }
    
    public void setUnivAddress(String univAddress) {
        this.univAddress = univAddress;
    }
    public String getUnivTelp() {
        return this.univTelp;
    }
    
    public void setUnivTelp(String univTelp) {
        this.univTelp = univTelp;
    }
    public String getUnivEmail() {
        return this.univEmail;
    }
    
    public void setUnivEmail(String univEmail) {
        this.univEmail = univEmail;
    }
    public String getUnivHomepage() {
        return this.univHomepage;
    }
    
    public void setUnivHomepage(String univHomepage) {
        this.univHomepage = univHomepage;
    }
    public int getNoAkreditasi() {
        return this.noAkreditasi;
    }
    
    public void setNoAkreditasi(int noAkreditasi) {
        this.noAkreditasi = noAkreditasi;
    }
    public String getAkreditasi() {
        return this.akreditasi;
    }
    
    public void setAkreditasi(String akreditasi) {
        this.akreditasi = akreditasi;
    }
    public Date getFoundDate() {
        return this.foundDate;
    }
    
    public void setFoundDate(Date foundDate) {
        this.foundDate = foundDate;
    }
    public String getRector() {
        return this.rector;
    }
    
    public void setRector(String rector) {
        this.rector = rector;
    }
    public Set<Staff> getStaffs() {
        return this.staffs;
    }
    
    public void setStaffs(Set<Staff> staffs) {
        this.staffs = staffs;
    }
    public Set<Faculty> getFaculties() {
        return this.faculties;
    }
    
    public void setFaculties(Set<Faculty> faculties) {
        this.faculties = faculties;
    }




}


